/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miniraknare;

import javax.swing.JOptionPane;

/**
 *
 * @author turha
 */
public class MiniraknareJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MiniraknareJFrame
     */
        double num, ans; 
        int calculation;
        public static double m = 0.0; //memory
    
    public MiniraknareJFrame() {
        initComponents();
    }
   
    
    public void arithmetic_operation(){
    
        switch(calculation){
            
        case 1 :  // addition +
            ans = num + Double.parseDouble(txfDisplay.getText());
            txfDisplay.setText(Double.toString(ans));
        break;
        
        case 2 :  // subtraktion -
            ans = num - Double.parseDouble(txfDisplay.getText());
            txfDisplay.setText(Double.toString(ans));
        break;
        
        case 3 :   // multiplikation *
            ans = num * Double.parseDouble(txfDisplay.getText());
            txfDisplay.setText(Double.toString(ans));
        break;
        
        case 4 :   // division /
            ans = num / Double.parseDouble(txfDisplay.getText());
            txfDisplay.setText(Double.toString(ans));
        break;
            
        case 5 :  // x^y 
           ans = Math.pow(num,Double.parseDouble(txfDisplay.getText()));
           txfDisplay.setText(String.valueOf(ans));
        break;
        }
        
    }
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfDisplay = new javax.swing.JTextField();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        BtnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnVarde = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnKomma = new javax.swing.JButton();
        eksi = new javax.swing.JButton();
        toplama = new javax.swing.JButton();
        carpi = new javax.swing.JButton();
        btnRoot = new javax.swing.JButton();
        btnLikaMed = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnXY = new javax.swing.JButton();
        btnMclear = new javax.swing.JButton();
        btnKup = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnMrecall = new javax.swing.JButton();
        btnKare = new javax.swing.JButton();
        btnMplus = new javax.swing.JButton();
        btnMminus = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bolu1 = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        lblM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txfDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDisplayActionPerformed(evt);
            }
        });

        btnOne.setBackground(new java.awt.Color(0, 102, 0));
        btnOne.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOne.setForeground(new java.awt.Color(255, 255, 255));
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setBackground(new java.awt.Color(0, 102, 0));
        btnTwo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(255, 255, 255));
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setBackground(new java.awt.Color(0, 102, 0));
        btnThree.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThree.setForeground(new java.awt.Color(255, 255, 255));
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnFour.setBackground(new java.awt.Color(0, 102, 0));
        btnFour.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnFour.setForeground(new java.awt.Color(255, 255, 255));
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setBackground(new java.awt.Color(0, 102, 0));
        btnFive.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnFive.setForeground(new java.awt.Color(255, 255, 255));
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        BtnSix.setBackground(new java.awt.Color(0, 102, 0));
        BtnSix.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BtnSix.setForeground(new java.awt.Color(255, 255, 255));
        BtnSix.setText("6");
        BtnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSixActionPerformed(evt);
            }
        });

        btnSeven.setBackground(new java.awt.Color(0, 102, 0));
        btnSeven.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSeven.setForeground(new java.awt.Color(255, 255, 255));
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setBackground(new java.awt.Color(0, 102, 0));
        btnEight.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEight.setForeground(new java.awt.Color(255, 255, 255));
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnNine.setBackground(new java.awt.Color(0, 102, 0));
        btnNine.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNine.setForeground(new java.awt.Color(255, 255, 255));
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnVarde.setBackground(new java.awt.Color(0, 102, 0));
        btnVarde.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVarde.setForeground(new java.awt.Color(255, 255, 255));
        btnVarde.setText("+/-");
        btnVarde.setPreferredSize(new java.awt.Dimension(39, 25));
        btnVarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVardeActionPerformed(evt);
            }
        });

        btnZero.setBackground(new java.awt.Color(0, 102, 0));
        btnZero.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnZero.setForeground(new java.awt.Color(255, 255, 255));
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnKomma.setBackground(new java.awt.Color(0, 102, 0));
        btnKomma.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKomma.setForeground(new java.awt.Color(255, 255, 255));
        btnKomma.setText(",");
        btnKomma.setPreferredSize(new java.awt.Dimension(39, 25));
        btnKomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKommaActionPerformed(evt);
            }
        });

        eksi.setBackground(new java.awt.Color(153, 0, 153));
        eksi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        eksi.setForeground(new java.awt.Color(255, 255, 255));
        eksi.setText("-");
        eksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eksiActionPerformed(evt);
            }
        });

        toplama.setBackground(new java.awt.Color(153, 0, 153));
        toplama.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        toplama.setForeground(new java.awt.Color(255, 255, 255));
        toplama.setText("+");
        toplama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toplamaActionPerformed(evt);
            }
        });

        carpi.setBackground(new java.awt.Color(153, 0, 153));
        carpi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        carpi.setForeground(new java.awt.Color(255, 255, 255));
        carpi.setText("*");
        carpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carpiActionPerformed(evt);
            }
        });

        btnRoot.setBackground(new java.awt.Color(153, 0, 153));
        btnRoot.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRoot.setForeground(new java.awt.Color(255, 255, 255));
        btnRoot.setText("√");
        btnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRootActionPerformed(evt);
            }
        });

        btnLikaMed.setBackground(new java.awt.Color(153, 0, 51));
        btnLikaMed.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLikaMed.setForeground(new java.awt.Color(255, 255, 255));
        btnLikaMed.setText("=");
        btnLikaMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikaMedActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 102, 102));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnXY.setBackground(new java.awt.Color(0, 102, 153));
        btnXY.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXY.setForeground(new java.awt.Color(255, 255, 255));
        btnXY.setText("x^y");
        btnXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXYActionPerformed(evt);
            }
        });

        btnMclear.setBackground(new java.awt.Color(0, 102, 153));
        btnMclear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMclear.setForeground(new java.awt.Color(255, 255, 255));
        btnMclear.setText("MC");
        btnMclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMclearActionPerformed(evt);
            }
        });

        btnKup.setBackground(new java.awt.Color(0, 102, 153));
        btnKup.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKup.setForeground(new java.awt.Color(255, 255, 255));
        btnKup.setText("x³");
        btnKup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupActionPerformed(evt);
            }
        });

        btnN.setBackground(new java.awt.Color(0, 102, 153));
        btnN.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnN.setForeground(new java.awt.Color(255, 255, 255));
        btnN.setText("n!");
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnMrecall.setBackground(new java.awt.Color(0, 102, 153));
        btnMrecall.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMrecall.setForeground(new java.awt.Color(255, 255, 255));
        btnMrecall.setText("MR");
        btnMrecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMrecallActionPerformed(evt);
            }
        });

        btnKare.setBackground(new java.awt.Color(0, 102, 153));
        btnKare.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKare.setForeground(new java.awt.Color(255, 255, 255));
        btnKare.setText("x²");
        btnKare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKareActionPerformed(evt);
            }
        });

        btnMplus.setBackground(new java.awt.Color(0, 102, 153));
        btnMplus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMplus.setForeground(new java.awt.Color(255, 255, 255));
        btnMplus.setText("M+");
        btnMplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMplusActionPerformed(evt);
            }
        });

        btnMminus.setBackground(new java.awt.Color(0, 102, 153));
        btnMminus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMminus.setForeground(new java.awt.Color(255, 255, 255));
        btnMminus.setText("M-");
        btnMminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMminusActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(102, 102, 0));
        btnLog.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("Log10");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(102, 102, 0));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("<--");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        bolu1.setBackground(new java.awt.Color(153, 0, 153));
        bolu1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bolu1.setForeground(new java.awt.Color(255, 255, 255));
        bolu1.setText("/");
        bolu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolu1ActionPerformed(evt);
            }
        });

        btnPi.setBackground(new java.awt.Color(102, 102, 102));
        btnPi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPi.setForeground(new java.awt.Color(255, 255, 255));
        btnPi.setText("π");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVarde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnThree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKomma, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(carpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toplama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRoot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bolu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLikaMed, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnXY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMclear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKare, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMplus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblM, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMrecall, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMminus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSix)
                                .addGap(8, 8, 8)
                                .addComponent(btnThree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKomma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSeven)
                                    .addComponent(btnEight))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFour)
                                    .addComponent(btnFive))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOne)
                                    .addComponent(btnTwo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnVarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZero)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnMminus)
                                .addComponent(btnMplus))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnMclear)
                                .addComponent(btnMrecall, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnXY)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnKup)
                                        .addComponent(btnKare))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnN)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLikaMed, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(toplama)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(carpi))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(bolu1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eksi)
                            .addGap(65, 65, 65))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblM, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        //Hämta från display
        String dis = txfDisplay.getText();
        //Lägger till en etta om det redan står "7" + "1" = "71"
        dis += "1";
        txfDisplay.setText(dis);
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        //istället jag skapar en variabel som har gjort på "1", jag skriver själv.
        txfDisplay.setText(txfDisplay.getText()+ "2");
        
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        txfDisplay.setText(txfDisplay.getText()+ "3");
        
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        txfDisplay.setText(txfDisplay.getText()+ "4");
        
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
       txfDisplay.setText(txfDisplay.getText()+ "5");
        
    }//GEN-LAST:event_btnFiveActionPerformed

    private void BtnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSixActionPerformed
        txfDisplay.setText(txfDisplay.getText()+ "6");
        
    }//GEN-LAST:event_BtnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        txfDisplay.setText(txfDisplay.getText()+ "7");
        
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        txfDisplay.setText(txfDisplay.getText()+ "8");
        
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        txfDisplay.setText(txfDisplay.getText()+ "9");
        
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnVardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVardeActionPerformed
       try { 
        double ops = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        ops =  ops * -1;
        txfDisplay.setText(String.valueOf(ops)); 
       }
       
       catch(java.lang.NumberFormatException e) {
           JOptionPane.showMessageDialog(null,"Du måste ange ett tal först."
                ,"Felmeddelande",JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_btnVardeActionPerformed

    private void btnKommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKommaActionPerformed
    
    txfDisplay.setText(txfDisplay.getText()+ ".");
    
    
    
        
    }//GEN-LAST:event_btnKommaActionPerformed

    private void carpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carpiActionPerformed
        num = Double.parseDouble(txfDisplay.getText());
        calculation = 3;
        txfDisplay.setText("");
        jLabel1.setText(num + "*");
        
        
        
    }//GEN-LAST:event_carpiActionPerformed

    private void toplamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toplamaActionPerformed
        num = Double.parseDouble(txfDisplay.getText());
        calculation = 1;
        txfDisplay.setText("");
        jLabel1.setText(num + "+");
        
    }//GEN-LAST:event_toplamaActionPerformed

    private void eksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksiActionPerformed
       num = Double.parseDouble(txfDisplay.getText());
        calculation = 2;
        txfDisplay.setText("");
        jLabel1.setText(num + "-");
        
        
    }//GEN-LAST:event_eksiActionPerformed

    private void btnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRootActionPerformed
      double ops = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        ops =  Math.sqrt(ops);
        txfDisplay.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_btnRootActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txfDisplay.setText("");
        jLabel1.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnKupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupActionPerformed
        double ops = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        ops = (ops * ops * ops);
        txfDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnKupActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int length = txfDisplay.getText().length();
        int number = txfDisplay.getText().length() - 1;
        String store;
        if (length > 0){
        StringBuilder back = new StringBuilder(txfDisplay.getText());
        back.deleteCharAt(number);
        store=back.toString();
        txfDisplay.setText(store);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLikaMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikaMedActionPerformed
      try
        {   arithmetic_operation();
            jLabel1.setText("");
         }
      
      catch (java.lang.NumberFormatException e) {
           JOptionPane.showMessageDialog(null,"Du måste ange andra tal."
                ,"Felmeddelande",JOptionPane.ERROR_MESSAGE);
      }
      //sparar ange tal inom decimal
      double decimal = Double.parseDouble(String.valueOf(txfDisplay.getText()));
      //jämför decimal till rullat av decimal och om det är inte oändlig 
        if ((decimal == Math.floor(decimal)) && !Double.isInfinite(decimal))
        {   //vi rullar och sätter decimal som int
            txfDisplay.setText((int)(decimal) + " ");
        }
        else { //eller som är en decimal om det krävs
            txfDisplay.setText(decimal + " ");
        }
    }//GEN-LAST:event_btnLikaMedActionPerformed

    private void btnKareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKareActionPerformed
        double ops = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        ops = (ops * ops);
        txfDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnKareActionPerformed

    private void bolu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolu1ActionPerformed
        num = Double.parseDouble(txfDisplay.getText());
        calculation = 4;
        txfDisplay.setText("");
        jLabel1.setText(num + "/");
    }//GEN-LAST:event_bolu1ActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        txfDisplay.setText(txfDisplay.getText()+ "0");
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        double ops = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        ops =  Math.log10(ops);
        txfDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        double ops;
        ops =  (3.1415926535897932);
        txfDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXYActionPerformed
        num = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        calculation = 5;
        txfDisplay.setText("");
        jLabel1.setText(num + "^");
    }//GEN-LAST:event_btnXYActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void btnMplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMplusActionPerformed
        double a = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        m = m + a;
        txfDisplay.setText("");
        lblM.setText(m + ""); 
    }//GEN-LAST:event_btnMplusActionPerformed

    private void btnMminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMminusActionPerformed
        double b = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        m = m - b;
        txfDisplay.setText("");
        lblM.setText(m + "");
    }//GEN-LAST:event_btnMminusActionPerformed

    private void btnMclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMclearActionPerformed
        m = 0;   //Just needed to equalize it to 0
        lblM.setText("");
    }//GEN-LAST:event_btnMclearActionPerformed

    private void btnMrecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMrecallActionPerformed
        txfDisplay.setText(lblM.getText());
    }//GEN-LAST:event_btnMrecallActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
      double number = Double.parseDouble(String.valueOf(txfDisplay.getText()));
      int factorial = 1;
     
      if (number == 0){
      factorial = 1; 
      }
      else {
       for(int a = 1; a <= number; a++)
      {
         factorial = factorial * a;
      }}
      txfDisplay.setText(Integer.toString(factorial));
    }//GEN-LAST:event_btnNActionPerformed

    private void txfDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDisplayActionPerformed
        
        /*
        double decimal = Double.parseDouble(String.valueOf(txfDisplay.getText()));
        if ((decimal == Math.floor(decimal)) && !Double.isInfinite(decimal))
        {
            txfDisplay.setText((int)(decimal) + " ");
        }
        else {
            txfDisplay.setText(decimal + " ");
        }
       */
       
        
    }//GEN-LAST:event_txfDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniraknareJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniraknareJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniraknareJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniraknareJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniraknareJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSix;
    private javax.swing.JButton bolu1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnKare;
    private javax.swing.JButton btnKomma;
    private javax.swing.JButton btnKup;
    private javax.swing.JButton btnLikaMed;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMclear;
    private javax.swing.JButton btnMminus;
    private javax.swing.JButton btnMplus;
    private javax.swing.JButton btnMrecall;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnRoot;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnVarde;
    private javax.swing.JButton btnXY;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton carpi;
    private javax.swing.JButton eksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblM;
    private javax.swing.JButton toplama;
    private javax.swing.JTextField txfDisplay;
    // End of variables declaration//GEN-END:variables
}
